# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-03-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('exercise_category', models.CharField(blank=True, default='', max_length=200)),
                ('html_text', models.CharField(blank=True, default='', max_length=2500)),
                ('js_text', models.CharField(blank=True, default='', max_length=2500)),
                ('css_text', models.CharField(blank=True, default='', max_length=2500)),
                ('additional_text', models.CharField(blank=True, default='', max_length=2500)),
                ('release_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
